config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  get 'about', to: "pages#about"
  resources :authors, only: [:index, :show, :edit, :update, :update] do
    scope module: :authors do
      resource :affiliations, only: [:edit, :update]
    end
   end
  resources :institution, only: [:index]
  resources :journals, only: [:index, :show, :edit, :update] do
    scope module: :journals do
      resources :publications, only: [:index] do
        collection do
          get 'year/:year', to: 'publications#year', as: "year"
        end
      end
    end
    get 'affinities', to: 'journals#affinities', as: "affinities"
  end
  resources :publications
  get :data, to: "data#index"
  resources :projects, only: [:index] do
    collection do
      get :journal_counts, to: "projects#journal_counts"
      get :publication_counts, to: "projects#publication_counts"
      get :gender_balance_chart, to: "projects#gender_balance_chart"
      get :where_do_they_publish, to: "projects#where_do_they_publish_show"
      post :where_do_they_publish, to: "projects#where_do_they_publish_query"
      get :journal_affinity, to: "projects#journal_affinity_show"
      post :journal_affinity, to: "projects#journal_affinity_query"
      get :title_ngram_chart, to: "projects#title_ngram_chart"
      post :title_ngram_chart, to: "projects#title_ngram_chart"
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  include Categorizable
  has_many :authorships, autosave: true
  has_many :authors, through: :authorships, autosave: true
  belongs_to :journal

  before_create :assign_cat
  validates :journal, presence: true

  scope :published_between, -> (years) { where(publication_year: years[0]...years[1]) }
  scope :year,              -> (value) { where(publication_year: value) }
  scope :articles,          -> { where(publication_type: "article") }
  scope :book_reviews,      -> { where(publication_type: "book_review") }
  scope :errata,            -> { where(publication_type: "errata") }

  def title?(string_to_match)
    titles == string_to_match
  end

  def one_page?
    pages && page_array.count > 1 &&
      (page_array[1] - page_array[0]).between?(0,1)
  end

  def page_array
    @page_arr ||= pages.split("-").map(&:to_i)
  end

  def any_volume_info?
    [volume, number, pages].none? &:blank?
  end

  def proper_title
    (display_title || title).to_s.html_safe
  end

  def author?(name_to_match)
    authors.any? { |a| a.name? name_to_match }
  end

  def journal?(title_to_match)
    journal.title == title_to_match
  end

  def assign_cat
    self.categorization = starting_cat
  end
end

app/controllers/journals/publications_controller.rb
class Journals::PublicationsController < ApplicationController
  before_action :set_show_values
  before_action :find_journal, only: [:index]

  def index
    @years = @journal.articles.order(publication_year: :desc).
                      group(:publication_year).
                      paginate(page: params[:page], per_page: 80)
  end

  def year
    @year = params[:year].to_i
    @journal = Journal.find(params[:journal_id])
    @publications = @journal.articles.where(publication_year: @year).
                             paginate(page: params[:page], per_page: 100).
                             order(:volume, :number, :pages, :title)
  end

  private

  def find_journal
    @journal = Journal.find(params[:journal_id])
  end

  def set_show_values
    @focused = "Data"
    @focused_datatype = "Journals"
  end

  def journal_params
    params.require(:journal).
           permit(:name, :publication_start, :publication_end, :display_name)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_show_values

  def index
    @search_string = params[:title]
    if @search_string
      @publications =  Publication.articles.where("COALESCE(display_title, title) ILIKE ?", "%#{@search_string&.split(" ")&.join("%")}%").
                                   includes(:authors, :journal).
                                   order(:title).paginate(page: params[:page], per_page: 5)
    else
       @publications = []
    end
    @none_found = @search_string && !@publications.exists?
  end

  def show
    @publication = Publication.find(params[:id])
    sift_categories(@publication)
  end

  def new
    @publication = Publication.new(publication_params)
  end

  def create
    attribute_values = publication_params
    @publication = Publication.create(attribute_values)
    authors = retrieve_authors
    @publication.update(authors: authors) unless authors.blank?
    authors.each { |author| CategoryReconciler.reconcile(@publication, author.cat) }
    CategoryReconciler.reconcile(@publication, @publication.journal.cat)
    redirect_to year_journal_publications_path(@publication.journal, @publication.publication_year)
  end

  def edit
    @publication = Publication.find(params[:id])
    @publication.display_title = @publication.display_title || @publication.title
  end

  def update
    @publication = Publication.find(params[:id])
    authors = retrieve_authors
    @publication.update_attributes(publication_params)
    @publication.update_attributes(authors: authors) unless authors.blank?
    redirect_to year_journal_publications_path(@publication.journal, @publication.publication_year)
  end

  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy
  end

  private

  def set_show_values
    @focused = "Data"
    @focused_datatype = "Publications"
  end

  def retrieve_authors
    authors = []
    @publication.authors.count.times do |idx|
      authors << Author.find_by(id: params["author_#{idx}"])
    end
    authors << Author.from_name(params["new_author_1"]) unless params["new_author_1"].blank?
    authors << Author.from_name(params["new_author_2"]) unless params["new_author_2"].blank?
    authors.compact
  end

  def publication_params
    params[:publication].permit(:publication_year, :title, :display_title, :publication_type, :volume, :number, :pages, :journal_id)
  end
end

app/views/publications/edit.html.slim
#content_div
  #display_panel
    h1= link_to @publication.proper_title, publication_path(@publication)
    h4.center Publication
    hr
    = simple_form_for @publication do |f|
      = f.input :display_title, wrapper_html: {class: 'line'}, placeholder: "Connectionism and Cognitive Architecture"
      .line
        = f.input :publication_year, label: "Year", as: :numeric, wrapper: false, placeholder: "1988", input_html: { style: "width: 8vw; margin-right: 2vw" , value: @publication.publication_year }
        span Journal &nbsp &nbsp
        h4.center= Journal.find(@publication.journal_id).proper_name
      .line
        = f.input :volume, label: "Vol.", as: :numeric, wrapper: false, placeholder: "28"
        = f.input :number, label: "Num.", wrapper: false, placeholder: "1-2", input_html: { style: "width: 4vw" }
        = f.input :pages,  label: "Pp.", wrapper: false, input_html: { style: "width: 8vw" }, placeholder: "28-71"
      .line
        = f.input :publication_type, as: :select, collection: ["article", "book review", "errata"]
      = f.input :journal_id, as: :hidden, input_html: { value: @publication.journal_id }
      .line
        label
          strong Authors
        - @publication.authors.each.with_index do |author, idx|
          .line
            label= link_to author.name, author_path(author)
            = check_box_tag "author_#{idx}", author.id, 1
      .line
        = text_field_tag "new_author_1", nil, placeholder: "new author"
      .line
        = f.submit

app/views/publications/index.html.slim
#content_div
  #display_panel
    h1 Publications
    hr
    p Enter a title in the search field to search the publications in the database.
    = form_tag publications_path, method: 'get'
      = text_field_tag "title", @search_string, class: "search", placeholder: "title"
      br
      = submit_tag "Search"
    - unless !@none_found && @publications.blank?
      h2.center Results:
      - if @none_found
        p.center None found
      - else
        table.standard
          - @publications.each do |publication|
            tr
              td= link_to publication.proper_title || "(title missing)", edit_publication_path(publication), class: "no_link_display"
              td= publication.authors.map(&:name).compact.join(", ")
              td= publication.journal.name

    / h1 Publications
    / hr
  - unless @publications.blank?
    footer
      = will_paginate @publications

app/views/publications/new.html.slim
#content_div
  #display_panel
    h1  New Publication
    h4.center Publication
    hr
    = simple_form_for @publication do |f|
      = f.input :title, wrapper_html: {class: 'line'}, placeholder: "Connectionism and Cognitive Architecture"
      .line
        = f.input :publication_year, label: "Year", as: :numeric, wrapper: false, placeholder: "1988", input_html: { style: "width: 8vw; margin-right: 2vw" , value: params[:publication_year] }
        span Journal &nbsp &nbsp
        h4.center= Journal.find(@publication.journal_id).proper_name
      .line
        = f.input :volume, label: "Vol.", as: :numeric, wrapper: false, placeholder: "28"
        = f.input :number, label: "Num.", wrapper: false, placeholder: "1-2", input_html: { style: "width: 4vw" }
        = f.input :pages,  label: "Pp.", wrapper: false, input_html: { style: "width: 8vw" }, placeholder: "28-71"
      .line
        = f.input :publication_type, as: :select, collection: ["article", "book review", "errata"]
      = f.input :journal_id, as: :hidden, input_html: { value: @publication.journal_id }
      .line
        label
          strong Authors
      .line
        = text_field_tag "new_author_1", nil, placeholder: "Jerry Fodor"
        | &nbsp &nbsp
        = text_field_tag "new_author_2", nil, placeholder: "Zenon Pylyshyn"
      .line
        = f.submit

app/views/publications/show.html.slim
#content_div
  #display_panel
    h1 #{@publication.title}
    h2.center Publication
    .center= link_to "(edit)", edit_publication_path(@publication)
    hr
    h2 Authors
    ul
      - @publication.authors.each do |author|
        li= link_to author.name, author_path(author)
    br
    h2 Data
    ul 
      li Journal: #{link_to @publication.journal.name, journal_path(@publication.journal)}
      li Volume: #{@publication.volume}
      li Number: #{@publication.number}
      li Pages: #{@publication.pages}
    br 
    h2 Categories
    = render "partials/categories"