config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  get 'about', to: "pages#about"
  resources :authors, only: [:index, :show, :edit, :update, :update] do
    scope module: :authors do
      resource :affiliations, only: [:edit, :update]
    end
   end
  resources :institution, only: [:index]
  resources :journals, only: [:index, :show, :edit, :update] do
    scope module: :journals do
      resources :publications, only: [:index] do
        collection do
          get 'year/:year', to: 'publications#year', as: "year"
        end
      end
    end
    get 'affinities', to: 'journals#affinities', as: "affinities"
  end
  resources :publications
  get :data, to: "data#index"
  resources :projects, only: [:index] do
    collection do
      get :journal_counts, to: "projects#journal_counts"
      get :publication_counts, to: "projects#publication_counts"
      get :gender_balance_chart, to: "projects#gender_balance_chart"
      get :where_do_they_publish, to: "projects#where_do_they_publish_show"
      post :where_do_they_publish, to: "projects#where_do_they_publish_query"
      get :journal_affinity, to: "projects#journal_affinity_show"
      post :journal_affinity, to: "projects#journal_affinity_query"
      get :title_ngram_chart, to: "projects#title_ngram_chart"
      post :title_ngram_chart, to: "projects#title_ngram_chart"
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/views/partials/_affiliations.html.slim
h3 Affiliations
table
  - @author.affiliations.each do |affiliation|
    tr
      td= affiliations.institution.name
      td= affiliations.start_date .sp affiliations.end_date

app/views/partials/_categories.html.slim
  h3 Categories
  br
  table
    - @categories.each do |cat|
      tr
        td= cat[0]
        td= cat[1]

app/views/partials/_data_specifier_bar.html.slim
.row#specifier_bar
  ul.menu
    li class=(@focused_datatype == "Authors" ? "focused" : :unfocused)
      = link_to "Authors", authors_path
    li class=(@focused_datatype == "Journals" ? "focused" : :unfocused)
      = link_to "Journals", journals_path
    li class=(@focused_datatype == "Publications" ? "focused" : :unfocused)
      = link_to "Publications", publications_path

app/views/partials/_project_specifier_bar.html.slim
.row#specifier_bar
  .two_columns
    ul.menu
      li.navigation_button#prev <<
      li class=(@focused_projects == "Where?" ? "focused" : :unfocused)
        = link_to "Where?", where_do_they_publish_projects_path
      li class=(@focused_projects == "Affinity" ? "focused" : :unfocused)
        = link_to "Affinity", journal_affinity_projects_path
      li class=(@focused_projects == "Journal Counts" ? "focused" : :unfocused)
        = link_to "J. Counts", journal_counts_projects_path
      li class=(@focused_projects == "Publication Counts" ? "focused" : :unfocused)
        = link_to "P. Counts", publication_counts_projects_path
      li class=(@focused_projects == "Gender Balance Chart" ? "focused" : :unfocused)
        = link_to "G. Balance", gender_balance_chart_projects_path
      li class=(@focused_projects == "Tile Ngram Chart" ? "focused" : :unfocused)
        = link_to "T. Ngrams", title_ngram_chart_projects_path
      li.navigation_button#next >>

javascript:
  document.querySelector("#prev").addEventListener("click", function(){
    project_buttons = document.querySelectorAll('#specifier_bar li:not(.navigation_button')
    first = project_buttons[0]
    parent = first.parentNode
    first.remove()
    parent.insertBefore(first, document.querySelector('#next'))
  })
  document.querySelector("#next").addEventListener("click", function(){
    project_buttons = document.querySelectorAll('#specifier_bar li:not(.navigation_button')
    last = project_buttons[project_buttons.length - 1]
    parent = last.parentNode
    last.remove()
    parent.insertBefore(last, project_buttons[0])
  })

app/views/partials/_pub_info.html.slim
td.tooltip.center
  - if publication.any_volume_info?
    .fa.fa-question-circle
    dl.tooltip_text
      - unless publication.volume.blank?
        dt volume
        dd= publication.volume
      br
      - unless publication.number.blank?
        dt number
        dd= publication.number
      br
      - unless publication.pages.blank?
        dt pages
        dd= publication.pages

app/views/partials/affiliations.html.slim
  h3 Affiliations
  table
    - @author.affiliations.each do |affiliation|
      tr
        td= affiliations.institution.name
        td= affiliations.start_date .sp affiliations.end_date