config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  get 'about', to: "pages#about"
  resources :authors, only: [:index, :show, :edit, :update, :update] do
    scope module: :authors do
      resource :affiliations, only: [:edit, :update]
    end
   end
  resources :institution, only: [:index]
  resources :journals, only: [:index, :show, :edit, :update] do
    scope module: :journals do
      resources :publications, only: [:index] do
        collection do
          get 'year/:year', to: 'publications#year', as: "year"
        end
      end
    end
    get 'affinities', to: 'journals#affinities', as: "affinities"
  end
  resources :publications
  get :data, to: "data#index"
  resources :projects, only: [:index] do
    collection do
      get :journal_counts, to: "projects#journal_counts"
      get :publication_counts, to: "projects#publication_counts"
      get :gender_balance_chart, to: "projects#gender_balance_chart"
      get :where_do_they_publish, to: "projects#where_do_they_publish_show"
      post :where_do_they_publish, to: "projects#where_do_they_publish_query"
      get :journal_affinity, to: "projects#journal_affinity_show"
      post :journal_affinity, to: "projects#journal_affinity_query"
      get :title_ngram_chart, to: "projects#title_ngram_chart"
      post :title_ngram_chart, to: "projects#title_ngram_chart"
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/models/author.rb
class Author < ActiveRecord::Base
  include Categorizable
  has_many :authorships
  has_many :affiliations
  has_many :publications, through: :authorships
  has_many :journals, through: :publications
  before_save :guess_gender

  scope :middle_initial_consistent, -> (mi) { where("middle_initial ~* ?", "^" + mi.to_s + ".*") }
  scope :having_five_pubs,          -> { joins(:authorships).group("authors.id").having("COUNT(authorships.id) > 5") }
  scope :published_in,              -> (journal) { joins(:journals).where("journals.id" => journal.id) }
  scope :with_name,                 -> (name) { where(first_name: parse_name(name)[0], middle_initial: parse_name(name)[1], last_name: parse_name(name)[2])}
  scope :with_name_like,            -> (name) {
                                                  where("first_name ILIKE ? 
                                                        #{"AND middle_initial ILIKE ?" if parse_name(name)[1]} 
                                                         AND last_name ILIKE ?", *(parse_name(name).map{|n| (n || "") + '%'}))
                                               }

  def self.find_or_create_by_name(name)
    name = parse_name(name)
    Author.find_or_create_by(first_name: name[0], middle_initial: name[1], last_name: name[2])
  end

  def name?(name_to_match)
    (first_name .sp last_name) == (name_to_match.split(" ")[0] .sp name_to_match.split(" ")[1]) ||
      (first_name .sp middle_initial .sp last_name == name_to_match)
  end

  def name
    first_name .sp middle_initial .sp last_name
  end

  def just_initials?
    not not
    (first_name&.strip || "").match(/(^$)|^(.|.\.)$/) &&
    (middle_initial&.strip || "").match(/(^$)|^(.|.\.)$/) &&
    (last_name&.strip || "").match(/(^$)|^(.|.\.)$/)
  end

  def merge_into(other_author)
    return unless self != other_author
    authorships.update_all(author_id: other_author.id)
    affiliations.update_all(author_id: other_author.id)
    other_author.birth_year = other_author.birth_year || birth_year
    other_author.death_year = other_author.death_year || death_year
    other_author.save
    destroy
  end

  def self.from_name(name)
    Author.with_name(name).first || 
      Author.create(first_name: parse_name(name)[0], middle_initial: parse_name(name)[1], last_name: parse_name(name)[2])
  end

  def active_range
    [
      publications.pluck(:publication_year).min,
      publications.pluck(:publication_year).max
    ]
  end

  def unity_rating
    pairs = journals.distinct.to_a.combination(2)
    return 0 if pairs.count == 0
    (pairs.sum {|a,b| a.co_publication_percentage(b)} / pairs.count).round(2)
  end

  def match?(other_author)
    match_by(other_author, :first_name) &&
      match_by(other_author, :middle_initial) &&
      match_by(other_author, :last_name)
  end

  private

  def match_by(other_author, name_part)
   return true unless send(name_part) && other_author.send(name_part)
   send(name_part).chomp(".").include?(other_author.send(name_part).chomp(".")) ||
     other_author.send(name_part).chomp(".").include?(send(name_part).chomp("."))
  end

  def guess_gender
    return if gender == 1 || gender == 0
    gender = Guess.gender(first_name)
    case gender[:gender]
    when "male"
      gender = gender[:confidence]
    when "female"
      gender = 1 - gender[:confidence]
    else
      gender = nil
    end
    self.gender = gender
  end

  def self.parse_name(name)
    names = name.split(" ")
    last_name = names.pop
    first_name = names.shift
    middle_initial = names.join(" ")
    [first_name, middle_initial, last_name]
  end
end

app/controllers/authors/affiliations_controller.rb
class Authors::AffiliationsController < ApplicationController
  def edit
    @author = @author.find_by(:author_id)
    @affiliations = @author.affiliations
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_show_values
  before_action :find_author, only: [:show, :edit, :update]

  def index
    @search_string = params[:name]
    @authors = @search_string ? Author.with_name_like(@search_string).paginate(page: params[:page], per_page: 6) : []
    @none_found = @search_string && !@authors.exists?
  
  end

  def show
    @publications = @author.publications.articles.
                            paginate(page: params[:page], per_page: 10).
                            order(:publication_year, :volume, :number, :pages)
    sift_categories(@author)
  end

  def edit
  end

  def update
    other_author = (Author.where(
                                   first_name: author_params[:first_name],
                                   middle_initial: author_params[:middle_initial],
                                   last_name: author_params[:last_name]
                                 ).to_a - [@author]).first
    unless other_author.blank?
      @author.merge_into(other_author)
      @author = other_author
    else
      @author.update_attributes(author_params)
    end
    redirect_to author_path(@author || other_author)
  end

  def find
  end

  private

  def find_author
    @author = Author.find(params[:id])
  end

  def set_show_values
    @focused = "Data"
    @focused_datatype = "Authors"
  end

  def author_params
    params.require(:author).
           permit(:first_name, :last_name, :middle_initial, :birth_year, :death_year)
  end
end

app/views/authors/edit.html.slim
#content_div
  #display_panel
    h1= link_to @author.name, author_path(@author)
    h2.center Author Edit
    hr
    = simple_form_for @author, html: {class: "center"} do |f|
      = f.input :first_name, wrapper_html: {class: 'line'}
      br
      = f.input :middle_initial, wrapper_html: {class: 'line'}
      br
      = f.input :last_name, wrapper_html: {class: 'line'}
      br
      .line
        = f.input :birth_year, as: :numeric, input_html: {class: 'year'}
        = f.input :death_year, as: :numeric, input_html: {class: 'year'}
      = f.submit

app/views/authors/find.html.slim
#content_div
  #display_panel
    h1 Authors
    hr
    p Enter a name in the search field to search the authors in the database. If you are unsure of the name, you can also enter initials.
    = form_tag authors_path, method: 'get'
      = text_field_tag "name", @search_string, class: "search", placeholder: "author name"
      = submit_tag "Search"
    - unless !@none_found && @authors.blank?
      h2.center Results:
      - if @none_found
        p.center None found
      ul.center class=('two_columns' if @authors.count > 5)
        - @authors.each do |author|
          li= link_to (author.first_name .sp author.middle_initial .sp author.last_name), author_path(author.id)

app/views/authors/index.html.slim
#content_div
  #display_panel
    h1 Authors
    hr
    p Enter a name in the search field to search the authors in the database.
    
    p If you are unsure of the name, you can also enter partial names or initials.
    = form_tag authors_path, method: 'get'
      = text_field_tag "name", @search_string, class: "search", placeholder: "author name"
      = submit_tag "Search"
    - unless !@none_found && @authors.blank?
      h2.center Results:
      - if @none_found
        p.center None found
      ul.center class=('two_columns' if @authors.count > 5)
        - @authors.each do |author|
          li= link_to (author.first_name .sp author.middle_initial .sp author.last_name), author_path(author.id)

    - unless @authors.blank?
      footer
        = will_paginate @authors

app/views/authors/show.html.slim
#content_div
  #display_panel
    h1= @author.name
    h4.center #{@author.birth_year || '?'} &#8212 #{@author.death_year}
    h2.center Author
    .center= link_to "(edit)", edit_author_path(@author)
    br
    .row.align_top
      .box width="50%"
        = render "partials/categories"
      .box width="50%"
        = render "partials/affiliations"
    hr
    h3 Publications
    table.standard
      tr
        th Year
        th Category
        th Title
        th Venue
        th 
        th colspan=3 Management
      - @publications.each do |publication|
        tr
          td= publication.publication_year
          td= publication.primary_category_name
          td= link_to publication.proper_title || "(title missing)", edit_publication_path(publication), class: "no_link_display"
          td= link_to publication.journal.name, year_journal_publications_path(publication.journal, publication.publication_year)
          = render 'partials/pub_info', publication: publication
          td= link_to "B", publication_path(publication, publication: { publication_type: "book review" } ), method: "patch", remote: true, data: { confirm: "Are you sure you want to mark this as a book review: #{publication.proper_title}" }, onclick: "history.go(0)"
          td= link_to "E", publication_path(publication, publication: { publication_type: "errata"} ), method: "patch", remote: true, data: { confirm: "Are you sure you want to mark this as errata: #{publication.proper_title}" }, onclick: "history.go(0)"
          td= link_to "X", publication_path(publication), method: "delete", remote: true, data: { confirm: "Are you sure you want to delete this: #{publication.proper_title}" }, onclick: "history.go(0)"
  footer
    = will_paginate @publications