config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  get 'about', to: "pages#about"
  resources :authors, only: [:index, :show, :edit, :update, :update] do
    scope module: :authors do
      resource :affiliations, only: [:edit, :update]
    end
   end
  resources :institution, only: [:index]
  resources :journals, only: [:index, :show, :edit, :update] do
    scope module: :journals do
      resources :publications, only: [:index] do
        collection do
          get 'year/:year', to: 'publications#year', as: "year"
        end
      end
    end
    get 'affinities', to: 'journals#affinities', as: "affinities"
  end
  resources :publications
  get :data, to: "data#index"
  resources :projects, only: [:index] do
    collection do
      get :journal_counts, to: "projects#journal_counts"
      get :publication_counts, to: "projects#publication_counts"
      get :gender_balance_chart, to: "projects#gender_balance_chart"
      get :where_do_they_publish, to: "projects#where_do_they_publish_show"
      post :where_do_they_publish, to: "projects#where_do_they_publish_query"
      get :journal_affinity, to: "projects#journal_affinity_show"
      post :journal_affinity, to: "projects#journal_affinity_query"
      get :title_ngram_chart, to: "projects#title_ngram_chart"
      post :title_ngram_chart, to: "projects#title_ngram_chart"
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  include Categorizable
  has_many :publications
  has_many :articles
  has_many :authors, through: :publications
  has_many :authorships, through: :publications

  def affinities
    Affinity.where(first_journal_id: id).or(Affinity.where(second_journal_id: id))
  end

  scope :empty, -> { where.not(id: Journal.joins(:publications).ids) }
  scope :where_cat, -> (cat, val) { Journal.where("CAST(categorization -> :cat AS integer) > :val", cat: cat, val: val) }



  def high_affinity_journals
    ids = affinities.where("affinity > 30 AND NOT affinity > 100").pluck(:first_journal_id, :second_journal_id).flatten.uniq
    Journal.where(id: ids)
  end

  def articles
    publications.articles
  end

  def article_authors
    Author.where(id: authorships.where(publication_id: articles.pluck(:id)).pluck(:author_id).uniq)
  end

  def years
    publication_start..(publication_end || 2017)
  end

  def self.condensed_name(name)
    cn = name.remove("The ", "A ", "'")
    cn = cn.split(":").first
    cn = cn.split("- ").first
    cn = cn.gsub("  ", " ")
    cn = cn.strip
  end

  def co_publication_percentage(other_journal)
    authors_count = authors.having_five_pubs.pluck(:id).count
    other_authors_count = other_journal.authors.having_five_pubs.pluck(:id).count
    # co_pub_ids = authors.merge(Author.group(:id).where("COUNT(authorships.id) > 5").pluck(:id) & other_journal.authors.pluck(:id)
    co_pub_ids = authors.having_five_pubs.pluck(:id) & other_journal.authors.having_five_pubs.pluck(:id)
    co_pub_authors_count = co_pub_ids.count
    (co_pub_authors_count.to_f * 100 / [authors_count, other_authors_count].min).round(2)
  end

  def proper_name
    display_name || name
  end
end

app/controllers/journals/publications_controller.rb
class Journals::PublicationsController < ApplicationController
  before_action :set_show_values
  before_action :find_journal, only: [:index]

  def index
    @years = @journal.articles.order(publication_year: :desc).
                      group(:publication_year).
                      paginate(page: params[:page], per_page: 80)
  end

  def year
    @year = params[:year].to_i
    @journal = Journal.find(params[:journal_id])
    @publications = @journal.articles.where(publication_year: @year).
                             paginate(page: params[:page], per_page: 100).
                             order(:volume, :number, :pages, :title)
  end

  private

  def find_journal
    @journal = Journal.find(params[:journal_id])
  end

  def set_show_values
    @focused = "Data"
    @focused_datatype = "Journals"
  end

  def journal_params
    params.require(:journal).
           permit(:name, :publication_start, :publication_end, :display_name)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_show_values
  before_action :find_journal, only: [:show, :edit, :update]
  include Categories

  def index
    @cat = params[:cat]; @val = params[:value]
    journals = @cat.blank? ? Journal : Journal.where_cat(@cat, @val)
    @journals = journals.order(:name).paginate(page: params[:page], per_page: 30)
  end

  def show
    @publication_count = @journal.articles.count
    sift_categories(@journal)
  end

  def edit
  end

  def update
    new_attrs = journal_params
    new_attrs[:display_name] = nil if new_attrs[:display_name] == @journal.name || new_attrs[:display_name] == ""
    @journal.update_attributes(new_attrs)
    redirect_to journal_path
  end

  def affinities
    @journal = Journal.find(params[:journal_id])
    @affinities = Affinity.for(@journal).includes(:journal_one, :journal_two).compact.
                          reject{ |a| a.affinity.nan? }.
                          sort_by(&:affinity).reverse
  end

  private

  def find_journal
    @journal = Journal.includes(:publications, :authors).find(params[:id])
  end

  def set_show_values
    @focused = "Data"
    @focused_datatype = "Journals"
  end

  def journal_params
    params.require(:journal).
           permit(:name, :publication_start, :publication_end, :display_name)
  end
end

app/views/journals/affinities.html.slim
#content_div
  #display_panel
    h1= link_to @journal.name, journal_path(@journal)
    h2.center Journal
    h2.center
    hr
    p See the #{link_to "project page", journal_affinity_projects_path} for details on the affinity calculations.
    table.standard.two_columns
      tbody
        - @affinities.each do |affinity|
          - next unless affinity.journal_one and affinity.journal_two
          tr
            td #{affinity.affinity}%
            - other_journal = ([affinity.journal_one, affinity.journal_two] - [@journal]).first
            td= link_to other_journal.name, journal_affinities_path(other_journal)

app/views/journals/edit.html.slim
#content_div
  #display_panel
    h1= @journal.proper_name
    h4.center Journal
    .center Article Count: #{@publication_count}
    hr
      = simple_form_for @journal, html: {class: "center"} do |f|
        = f.input :name, wrapper_html: {class: 'line'}
        = f.input :display_name, wrapper_html: {class: 'line'}
        = f.input :publication_start, as: :numeric, wrapper_html: {class: 'line'}
        = f.input :publication_end, as: :numeric, wrapper_html: {class: 'line'}
        = f.submit

app/views/journals/index.html.slim
#content_div
  #display_panel
    h1 Journals
    hr
    = form_tag journals_path, method: :get
      .line
        .column
          label Filter Category
          br
          = select_tag "cat", options_for_select(CATEGORIES.invert.merge(none: ""), @cat)
        .column
          label Threshold Value
          br
          = select_tag "value", options_for_select([10, 25, 50], @val)
        .column
          = submit_tag "Filter by category"
    ul.two_columns
      - @journals.each do |journal|
        li= link_to journal.proper_name, journal_path(journal)

  footer
    = will_paginate @journals

app/views/journals/show.html.slim
#content_div
  #display_panel
    h1 #{@journal.proper_name}
    h4.center Journal
    br
    br
    br
    .row.align_top
      .box width="30%"
        h3
          u Navigation
        br
        = link_to "Edit Journal", edit_journal_path(@journal)
        br
        br
        = link_to "New Publication", new_publication_path(publication: { journal_id: @journal.id })
        br
        br
        = link_to "View Affinities", journal_affinities_path(@journal)
        br
        br
        = link_to "View Publications (by Year)", journal_publications_path(@journal)

      .dashed_box
        h3 Statistics
        br
        table
          tr
            td Article Count: 
            td #{@journal.articles.count}
          tr
          tr
          tr
            td Author Count: 
            td #{@journal.article_authors.uniq.count}
          tr
          tr 
          tr 
            td Active Years: 
            td #{@journal.publication_start || '?'} - #{@journal.publication_end}
      .dashed_box
        = render "partials/categories"

app/views/journals/year.html.slim
#content_div
  #display_panel
    - if params[:page].nil? || params[:page] == "1"
      h1 = link_to @journal.name, journal_path(@journal)
      h2.center Journal
      h2.center
        = link_to @year - 1, journal_year_path(@journal, @year - 1), class: "small-year"
        = @year
        = link_to @year + 1, journal_year_path(@journal, @year + 1), class: "small-year"
      .center Article Count: #{@publications.count}
      hr
    table.standard.two_columns
      tbody
        - @publications.each do |publication|
          tr
            td= link_to publication.proper_title || "(title missing)", edit_publication_path(publication), class: "no_link_display"
            td 
              - publication.authors.each.with_index do |author, idx|
                = link_to author.name, author_path(author)
                - if idx + 1 < publication.authors.count && publication.authors.count > 1
                  | , 
            td= link_to "B", publication_path(publication, publication: { publication_type: "book review" } ), method: "patch", remote: true, data: { confirm: "Are you sure you want to mark this as a book review: #{publication.proper_title}" }, onclick: "history.go(0)"
            td= link_to "E", publication_path(publication, publication: { publication_type: "errata"} ), method: "patch", remote: true, data: { confirm: "Are you sure you want to mark this as errata: #{publication.proper_title}" }, onclick: "history.go(0)"
            td= link_to "X", publication_path(publication), method: "delete", remote: true, data: { confirm: "Are you sure you want to delete this: #{publication.proper_title}" }, onclick: "history.go(0)"

  footer
    = will_paginate @publications